# Generated by Django 5.1.6 on 2025-05-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caldos_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disponibilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoDisponivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_disponivel_em_gramas", models.IntegerField()),
                (
                    "disponibilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="caldos_backend.disponibilidade",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caldos_backend.produto",
                    ),
                ),
            ],
        ),
    ]
