# Generated by Django 5.2 on 2025-05-07 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("caldos_backend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pessoa",
        ),
    ]
