# Generated by Django 5.1.6 on 2025-05-07 16:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caldos_backend", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="tamanhos_disponiveis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.CreateModel(
            name="ProdutosDisponveis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_disponibilidade", models.DateField()),
                ("tamanho", models.CharField(max_length=255)),
                ("quantidade", models.IntegerField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caldos_backend.produto",
                    ),
                ),
            ],
        ),
    ]
