# Generated by Django 5.1.6 on 2025-05-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caldos_backend", "0004_produto_tamanhos_disponiveis_produtosdisponveis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tamanhos_disponiveis",
        ),
        migrations.AddField(
            model_name="produto",
            name="precos_por_tamanho",
            field=models.JSONField(default=dict),
        ),
    ]
