# Generated by Django 5.1.6 on 2025-05-07 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("caldos_backend", "0005_remove_produto_tamanhos_disponiveis_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="precos_por_tamanho",
            new_name="precos_em_centavos_por_tamanho",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="preco_em_centavos",
        ),
    ]
